version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sqlite.db:/app/sqlite.db
    environment:
      - NODE_ENV=production
