FROM node:20.9-alpine

WORKDIR /socket
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
COPY tsconfig.json ./

EXPOSE 8000
CMD ["pnpm", "socket"]
